name: Build Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: This releases version name
        default: "1.00 - Stable"
      versionCode:
        required: true
        description: This releases version code
        default: "1000"
      title:
        required: true
        description: Title of this release
      description:
        required: false
        description: Description of this release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set Version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionCode: ${{github.event.inputs.versionCode}}
        versionName: ${{github.event.inputs.versionName}}

    - name: Build Signed APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore: ${{ secrets.keystore }}
        keystore_password: ${{ secrets.keystore_password }}
        key_alias: ${{ secrets.key_alias }}
        key_password: ${{ secrets.key_password }}
        
    - name: Release
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        tag="${{ github.event.inputs.versionName }}"
        git tag "$tag"
        git push origin "$tag"
        gh release create "$tag" \
          --title "${{ github.event.inputs.title }}" \
          --notes "${{ github.event.inputs.description }}" \
          app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
