name: Build Debug

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SHA6: ${GITHUB_SHA::6}
    steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set Version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionName: "1.00 - $SHA6"
        
    - name: Build Debug APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
