name: Crowdin Action

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/src/main/res/values/strings.xml'
      - '.github/workflows/crowdin.yml'
  schedule:
    - cron: "0 17 * * 6"
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Crowdin Action
        uses: crowdin/github-action@1.4.7
        with:
          config: crowdin.yml
          upload_translations: true
          download_translations: true
          push_translations: true
          create_pull_request: false
          localization_branch_name: l10n
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: 507180
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Merge
        run: |
          sudo chmod -R ugo+rwX .
          git checkout main
          git add *
          git merge l10n
          git push